---
depends_on: []
kind: pipeline
name: test
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - go run honnef.co/go/tools/cmd/staticcheck ./...
  image: golang:1.16
  name: staticcheck
  volumes:
  - name: gopath
    path: /go
- commands:
  - go run golang.org/x/lint/golint -set_exit_status ./...
  image: golang:1.16
  name: lint
  volumes:
  - name: gopath
    path: /go
- commands:
  - go vet ./...
  image: golang:1.16
  name: vet
  volumes:
  - name: gopath
    path: /go
- commands:
  - go test -cover ./...
  image: golang:1.16
  name: test
  volumes:
  - name: gopath
    path: /go
trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  - refs/pull/**
volumes:
- name: gopath
  temp: {}
---
depends_on:
- test
kind: pipeline
name: docs
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - markdownlint 'README.md' 'CONTRIBUTING.md'
  image: thegeeklab/markdownlint-cli
  name: markdownlint
- commands:
  - npm install -g spellchecker-cli
  - spellchecker --files 'README.md' 'CONTRIBUTING.md' -d .dictionary -p spell indefinite-article
    syntax-urls --no-suggestions
  environment:
    FORCE_COLOR: true
    NPM_CONFIG_LOGLEVEL: error
  image: node:lts-alpine
  name: spellcheck
trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  - refs/pull/**
---
depends_on:
- docs
kind: pipeline
name: notifications
platform:
  arch: amd64
  os: linux
steps:
- image: plugins/matrix
  name: matrix
  settings:
    homeserver:
      from_secret: matrix_homeserver
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    template: 'Status: **{{ build.status }}**<br/> Build: [{{ repo.Owner }}/{{ repo.Name
      }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}<br/> Message:
      {{ build.message }}'
    username:
      from_secret: matrix_username
  when:
    status:
    - success
    - failure
trigger:
  ref:
  - refs/heads/main
  - refs/tags/**
  status:
  - success
  - failure
---
kind: signature
hmac: 758e035deda2239882aef0b1654916e376f5959883149f109dcb59a30faa9d96

...
